# Site settings
title: Mengman Liu
description: 'Personal website of Mengman Liu'
url: 'https://GcarolD.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'
# disable_landing_page: true

author:
  name: 'Mengman Liu'
  scholar_username: OOItML4AAAAJ&hl=zh-CN
  email: liumengman@seu.edu.cn
  github_username:  GcarolD
  linkedin_username:  Mengman Liu
  orcid_username:  0009-0003-0575-4186

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

# 自定义文件夹
collections:
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/